"""Source-linked LMS recipes. Claims describe videos, never guaranteed results.

Undefined windows use the host app's available pre-game history. Missing
mandatory inputs block qualification. These rules never modify host boards.
"""

def gate(field, label, op, value, kind="number"):
    return {"field": field, "label": label, "op": op, "value": value, "type": kind}


def recipe(key, name, market, side, video, claim, rules=(), *,
           line=None, edge=None, rate=None, kind="SINGLE", notes=()):
    return {
        "id": key, "name": name, "market": market, "side": side,
        "source_url": "https://www.youtube.com/watch?v=" + video,
        "claim": claim, "rules": list(rules), "exact_line": line,
        "edge_min": edge, "rate_min": rate, "kind": kind,
        "adaptations": [
            "LMS adaptation: exact-line empirical hit rate from the app's "
            "available pre-game history, not an independently calibrated probability.",
            "LMS adaptation: all eligible candidate singles are recorded without "
            "a Top 10 cap; genuine same-line/side/book prices are required.",
        ] + list(notes),
    }


G = gate
CATALOGUE = {
    "nfl": [
        recipe("kicker_rank", "Kicker Points Over — rankings", "kicker_points", "OVER",
               "KJKFuo4XPXY", "Author claims 87% for the method.",
               [G("opponent_kicker_points_rank", "Opponent kicker-points allowance: bottom five", ">=", 28),
                G("opponent_fg_points_per_attempt_rank", "Opponent FG-points/attempt allowance: bottom ten", ">=", 23),
                G("offense_fg_attempts_rank", "Offense FG attempts/game: top ten", "<=", 10),
                G("kicker_accuracy_rank", "Kicker FG conversion: top ten", "<=", 10)], edge=0),
        recipe("rb_under", "RB Rushing Yards Under", "rushing_yards", "UNDER",
               "aLI528uPCoA", "Author claims 80% for this method.",
               [G("position", "Running back", "==", "RB", "text"),
                G("rush_defense_rank", "Opponent rush defense: top five", "<=", 5),
                G("baseline_below_line", "Carries × YPC projection below the quote", "==", True, "boolean")],
               edge=0,
               notes=["Rush-defense ranking uses the host app's positional yards-allowed convention."]),
        recipe("rb_over", "RB Rushing Yards Over", "rushing_yards", "OVER",
               "rccTigVEJu4", "Author claims 85% for this method.",
               [G("position", "Running back", "==", "RB", "text"),
                G("rush_projection_above_line", "Average of own/opponent YPC projections above line", "==", True, "boolean")],
               edge=0),
        recipe("wr_over", "WR Receiving Yards Over", "receiving_yards", "OVER",
               "WO-BY_28oM4", None,
               [G("position", "Wide receiver", "==", "WR", "text"),
                G("target_share", "Target share at least 27%", ">=", .27),
                G("opponent_yards_per_completion", "Opponent allows at least 11 yards/completion", ">=", 11),
                G("stable_role", "Verified stable role", "==", True, "boolean")],
               edge=0, kind="RESEARCH",
               notes=["Coverage context: an 80%+ method-success claim has not been authenticated for this lesson."]),
        recipe("wr_under", "WR Receiving Yards Under", "receiving_yards", "UNDER",
               "zVI0pbdQB4k", "Author claims 82%; defense wording is contradictory.",
               [G("position", "Wide receiver", "==", "WR", "text"),
                G("wr_defense_rank", "Strong WR defense: top five", "<=", 5),
                G("opponent_yards_per_completion_rank", "Lowest yards/completion allowed: top five", "<=", 5),
                G("defense_direction_verified", "Ranking interpretation explicitly verified", "==", True, "boolean")],
               edge=0,
               notes=["Contradictory source language is not silently resolved. A verified direction input is mandatory."]),
        recipe("qb_td", "QB 1+ Passing Touchdown", "passing_tds", "OVER",
               "9R5P42vMejw", "Author describes 90–100% historical success.",
               [G("position", "Quarterback", "==", "QB", "text"),
                G("opponent_passing_td_per_game", "Opponent allows at least 1.7 passing TD/game", ">=", 1.7),
                G("verified_nonrookie", "Verified non-rookie QB", "==", True, "boolean"),
                G("verified_starter", "Verified starter, not backup", "==", True, "boolean")],
               line=.5, rate=.9, edge=0,
               notes=["Available exact-line history is an adaptation; it is not a newly invented comparable-defense model."]),
        recipe("qb_yards_td", "QB Passing Yards + Passing TD — candidate singles",
               "passing_yards", "OVER", "awDLJlH-Uy0",
               "Related lesson claims at least 90% season yardage success.",
               [G("position", "Quarterback", "==", "QB", "text"),
                G("weak_pass_defense_verified", "Verified weak passing-defense matchup", "==", True, "boolean")],
               rate=.9, edge=0, kind="CANDIDATE_LEG",
               notes=["Adapted single-leg research tracking, NOT an actual yardage+TD parlay. No joint probability or SGP profit is asserted."]),
        recipe("qb_wr", "QB + WR Yardage — candidate singles", "receiving_yards", "OVER",
               "dwuHJlEWJpQ", "One variant claims at least 80% combined success.",
               [G("position", "Primary wide receiver", "==", "WR", "text"),
                G("primary_receiver_verified", "Verified primary receiver paired with his QB", "==", True, "boolean"),
                G("weak_pass_defense_verified", "Verified weak passing-defense matchup", "==", True, "boolean")],
               rate=.9, edge=0, kind="CANDIDATE_LEG",
               notes=["Tracks qualifying candidate singles separately; actual correlated QB/WR parlays are not synthesized."]),
        recipe("kicker_accuracy", "Kicker FG Accuracy — coverage context", "kicker_points", "OVER",
               "tCH6dKye_8E", None, kind="RESEARCH",
               notes=["The 90% figure is field-goal accuracy, not a kicking-points Over hit rate."]),
        recipe("first_half", "First-half Totals — coverage context", "first_half_total", "UNDER",
               "3YcOcgTLHTQ", None, kind="RESEARCH",
               notes=["Ranking wording and the method-success claim remain unresolved."]),
    ],
    "nba": [
        recipe("rebounds", "Starting Team-Leader Rebounds Over", "rebounds", "OVER",
               "oRtjseFNwn0", "Author claims an 85% win rate.",
               [G("verified_starter", "Verified starting player", "==", True, "boolean"),
                G("team_rebound_leader", "Team-leading rebounder", "==", True, "boolean"),
                G("opponent_offensive_rebound_allowance_rank", "Opponent OREB allowance: bottom ten", ">=", 21),
                G("opponent_defensive_rebound_allowance_rank", "Opponent DREB allowance: bottom ten", ">=", 21),
                G("opponent_fga_rank", "Opponent FGA: top fifteen", "<=", 15),
                G("opponent_fg_pct_rank", "Opponent FG%: bottom fifteen", ">=", 16)], edge=0,
               notes=["Own rebounds are never substituted for opponent rebound allowances. Starter status is not inferred from minutes."]),
        recipe("pra_legs", "One-player P/R/A — candidate singles",
               ("points", "rebounds", "assists"), "OVER", "qaJecoSXUBU",
               "Author claims 80% for the parlay and 90% per selected leg.",
               [G("dominant_usage_verified", "Verified dominant/high-usage player", "==", True, "boolean"),
                G("opponent_positional_fantasy_allowance_rank", "Positional fantasy allowance: bottom five", ">=", 26)],
               rate=.9, kind="CANDIDATE_LEG",
               notes=["Adapted candidate-single tracking only. No independence assumption, combined probability or fabricated parlay quote."]),
        recipe("points_under", "Low-usage Starter Points Under — coverage context", "points", "UNDER",
               "TDsm0vE2wXk", None,
               [G("verified_starter", "Verified starter", "==", True, "boolean"),
                G("starting_five_usage_rank", "Usage rank fourth/fifth among starters", ">=", 4),
                G("strong_positional_defense_verified", "Verified strong positional defense", "==", True, "boolean")],
               edge=.03, kind="RESEARCH",
               notes=["The captured 85% passage describes price-implied probability, not an authenticated 80%+ success claim."]),
        recipe("pra_projection", "Projection-supported P/R/A — coverage context", "points", "OVER",
               "2dEGauXhljY", None, kind="RESEARCH",
               notes=["Projected minutes × fantasy points does not establish a correlated parlay probability."]),
        recipe("live_pra", "Live PRA Entry", "pra", "OVER", "o0fLpbF9SdI",
               None, kind="LIVE", notes=["Requires a verified live entry and live quote; never emitted as a pregame pick."]),
        recipe("live_middle", "Live Total Middling", "total_points", "OVER", "c5P3woi1Kyw",
               None, kind="LIVE", notes=["Requires both real entries, prices and live timestamps."]),
        recipe("live_hedge", "Live Moneyline Hedge", "moneyline", "OVER", "RUEbuNLFQZQ",
               None, kind="LIVE", notes=["Requires a live position and actual hedge price; not an ordinary pregame bet."]),
        recipe("pace_total", "Efficiency/Pace Game Total — coverage context", "total_points", "OVER",
               "pVt1VOM1ep8", None, kind="RESEARCH"),
    ],
    "mlb": [
        recipe("batter_hits_under", "Batter Under 1.5 Hits", "hits", "UNDER",
               "2t1nVxeFHm8", "Author claims an 85% win rate.",
               [G("facing_highest_owned_dfs_pitcher", "Facing highest-owned DFS pitcher on this slate", "==", True, "boolean"),
                G("career_ba_vs_pitcher", "Career BA vs starter at most .200", "<=", .2),
                G("career_ab_vs_pitcher", "Career AB vs starter at least five", ">=", 5),
                G("bullpen_ba_allowed_rank", "Opposing bullpen BA allowed: top ten", "<=", 10)],
               line=1.5,
               notes=["DFS ownership must be sourced, not replaced with a pitcher-quality proxy."]),
        recipe("pitcher_hits_over", "Pitcher Hits Allowed Over", "hits_allowed", "OVER",
               "hGuyyt2Xkcw", "Source discusses a high historical exact-line hit rate.",
               [G("opponent_moneyline", "Opponent genuine moneyline at most -200", "<=", -200),
                G("opponent_team_ba_rank", "Opponent team BA: top ten", "<=", 10)],
               edge=0,
               notes=["Author probability examples are not an independently verified method-wide success rate."]),
        recipe("pitcher_hits_under", "Two-pitcher Hits Allowed Under — candidate singles",
               "hits_allowed", "UNDER", "tw56xrzkXlU", "Author claims 90% for the illustrated two-leg parlay.",
               [G("slate_pitcher_rank", "Verified top-two slate pitcher", "<=", 2),
                G("opponent_hits_per_game_rank", "Opponent hits/game: bottom ten", ">=", 21)],
               rate=.9, kind="CANDIDATE_LEG",
               notes=["Top-two ranking needs an explicit sourced definition. Qualifying singles are adapted leg tracking, not a priced parlay."]),
        recipe("no_hr", "No-HR Parlay — candidate singles", "home_runs", "UNDER",
               "9CRGk1F6DU4", "Author claims 90% for the parlay; selects roughly 94%+ no-HR legs.",
               [G("opponent_pitcher_hr9_rank", "Verified low-HR/9 starter: top fifteen", "<=", 15),
                G("hr9_direction_verified", "Ambiguous HR/9 rank direction explicitly verified", "==", True, "boolean"),
                G("career_hr_vs_pitcher", "Zero career home runs vs starter", "==", 0),
                G("career_matchup_verified", "Career matchup queried successfully", "==", True, "boolean")],
               line=.5, rate=.94, kind="CANDIDATE_LEG",
               notes=["94% inclusive follows the shown example; this adaptation is explicit. No combined parlay probability or payout is invented."]),
        recipe("team_runs", "Team Over 1.5 Runs", "team_runs", "OVER",
               "emeoXTN9wt4", "Source evaluates high-probability team-run alternates.",
               [G("team_runs_rank", "Offense runs/game: top ten", "<=", 10),
                G("team_hr_rank", "Offense HR/game: top ten", "<=", 10),
                G("opponent_starter_era", "Opposing starter ERA at least four", ">=", 4),
                G("opponent_starter_hr9", "Opposing starter HR/9 at least 1.4", ">=", 1.4),
                G("opponent_bullpen_era_rank", "Opposing bullpen ERA: bottom ten", ">=", 21),
                G("park_factor", "Park factor at least 100", ">=", 100)], line=1.5, edge=0),
        recipe("game_total_over", "Alternate Game Total Over", "total_runs", "OVER",
               "l78HMb0zrz4", "Method selects H2H patterns of at least eight in ten.",
               [G("h2h_sample", "Ten comparable H2H games", ">=", 10),
                G("h2h_over_hits", "At least eight H2H Overs at this exact line", ">=", 8),
                G("both_starters_era_min", "Both starters ERA at least four", ">=", 4),
                G("over_environment_verified", "Bullpens, park and HR/9 align with Over", "==", True, "boolean")],
               notes=["Undefined environment cutoffs require verified explicit inputs."]),
        recipe("game_total_under", "Alternate Game Total Under", "total_runs", "UNDER",
               "l78HMb0zrz4", "Method selects H2H patterns of at least eight in ten.",
               [G("h2h_sample", "Ten comparable H2H games", ">=", 10),
                G("h2h_under_hits", "At least eight H2H Unders at this exact line", ">=", 8),
                G("both_starters_era_max", "Both starters ERA at most three", "<=", 3),
                G("under_environment_verified", "Bullpens, park and HR/9 align with Under", "==", True, "boolean")],
               notes=["Undefined environment cutoffs require verified explicit inputs."]),
        recipe("projected_total", "Projected Game Totals — coverage context", "total_runs", "OVER",
               "vdoxBu_Xb1E", None, kind="RESEARCH",
               notes=["A .75-run projected gap is not itself an 80% hit-rate claim."]),
    ],
    "nhl": [
        recipe("pp1_points", "PP1 Over 0.5 Points", "points", "OVER",
               "CLuLX0M834I", "Author claims an 85% win rate.",
               [G("power_play_unit", "Verified PP1 assignment", "==", 1),
                G("team_points_rank", "Top one/two team scorers", "<=", 2),
                G("opponent_pim_rank", "Opponent penalty minutes: top five", "<=", 5),
                G("team_power_play_rank", "Own power-play percentage: top ten", "<=", 10)],
               line=.5, edge=0,
               notes=["PP time alone never establishes a verified PP1 assignment."]),
        recipe("pp2_points", "PP2 Under 1.5 Points — candidate singles", "points", "UNDER",
               "WpOHTGsDo6c", "Author claims 90% for the parlay.",
               [G("power_play_unit", "Verified PP2 assignment", "==", 2),
                G("opponent_goals_allowed_rank", "Opponent goals allowed: top five", "<=", 5),
                G("opponent_penalty_kill_rank", "Opponent penalty kill: top five", "<=", 5),
                G("opponent_goalie_confirmed", "Confirmed opposing starting goalie", "==", True, "boolean")],
               line=1.5, kind="CANDIDATE_LEG",
               notes=["Uses ranking gates rather than the example's approximate GA/PK figures. All candidate singles are tracked; no invented two-leg payout/probability."]),
        recipe("shots", "High-volume Shooter Alternate Over", "shots", "OVER",
               "4yKDIh3GSws", "Separate Brady Tkachuk 2+ SOG example claims 90%+.",
               [G("high_volume_shooter_verified", "Verified high-volume shooter", "==", True, "boolean"),
                G("line_below_average", "Quoted line below the available pre-game average", "==", True, "boolean")],
               notes=["The general SOG lesson supplies the below-average rule. The 90%+ statement is a separate testimonial, not a universal 90% qualification gate.",
                      "Additional claim source: https://www.youtube.com/watch?v=t_l3oBJZd2Q"]),
        recipe("points_matchup", "Player Point Over — matchup adaptation", "points", "OVER",
               "_Z5ZM_7Nozo", "The example increases 71% to 81% against similar defenses.",
               [G("comparable_defense_matchup_verified", "Comparable-defense matchup explicitly verified", "==", True, "boolean")],
               line=.5, edge=0,
               notes=["No arbitrary ten-point probability bonus is copied from an isolated example. The app's exact-line history supplies the estimate."]),
        recipe("total_under", "Opening 5.5 → Alternate Full-game Under", "total_goals", "UNDER",
               "GtUr_qGv4cU", "Source requires at least eight aligned H2H games in ten.",
               [G("opening_total", "Verified opening total 5.5", "==", 5.5),
                G("h2h_sample", "Ten H2H games", ">=", 10),
                G("h2h_under_hits", "Eight of ten Under this exact threshold", ">=", 8),
                G("line_movement_aligned", "No contrary movement from verified opening quote", "==", True, "boolean")],
               line=7, notes=["Integer-line pushes are graded separately, never counted as wins."]),
        recipe("total_over", "Opening 6.5 → Alternate Full-game Over", "total_goals", "OVER",
               "GtUr_qGv4cU", "Source requires at least eight aligned H2H games in ten.",
               [G("opening_total", "Verified opening total 6.5", "==", 6.5),
                G("h2h_sample", "Ten H2H games", ">=", 10),
                G("h2h_over_hits", "Eight of ten Over this exact threshold", ">=", 8),
                G("line_movement_aligned", "No contrary movement from verified opening quote", "==", True, "boolean")],
               line=5),
        recipe("h2h_under", "H2H Full-game Under 7.5", "total_goals", "UNDER",
               "Admm5JRXRUI", "Author claims 90% from nine of ten H2H games.",
               [G("h2h_sample", "Ten H2H games", ">=", 10),
                G("h2h_under_hits", "Nine of ten Under 7.5", ">=", 9)],
               line=7.5,
               notes=["Does not import the older opening-total or movement gates into this separate example."]),
        recipe("first_period", "First-period Under 2.5", "first_period_goals", "UNDER",
               "TkKc1FxqkqU", "Author claims 83% season / 90% H2H in the example.",
               [G("first_period_history_verified", "Exact first-period goal history verified", "==", True, "boolean")],
               line=2.5,
               notes=["Use the exact Under 2.5 event, not the narration's different 'over three' event. No unexplained blend or 3–7% edge is copied."]),
        recipe("saves", "Goalie Saves Over — coverage context", "saves", "OVER",
               "FTspdQ2D3GQ", None, kind="RESEARCH",
               notes=["Opponent shot-volume advice is documented, but no 80%+ claim or numerical selection rule is verified. Confirmed starters remain mandatory."]),
        recipe("regulation", "Regulation Winner — coverage context", "regulation_win", "OVER",
               "zbm0lZcUjL4", None, kind="RESEARCH",
               notes=["Cheaper regulation odds do not establish an 80%+ win rate or positive edge. Regulation and overtime winners are different outcomes."]),
    ],
}