services:
  - type: web
    name: nhl-shots-picks
    env: python
    region: oregon
    plan: starter
    buildCommand: bash build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USERS
        sync: false
      - key: STATMUSE_EMAIL
        sync: false
      - key: STATMUSE_PASSWORD
        sync: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.browsers
